<?php

/**
 * @file
 * Provides functionality for the Vosix Components Button module.
 */

/**
 * Implements hook_preprocess_paragraph__HOOK().
 */
function vosix_components_button_preprocess_paragraph__button(array &$variables) {
  /** @var \Drupal\paragraphs\Entity\Paragraph|null $paragraph */
  $paragraph = $variables['paragraph'] ?? NULL;
  if (!$paragraph) {
    return;
  }

  if ($paragraph->hasField('field_outline')) {
    $outline = $variables['content']['field_outline']; 
    $variables['outline'] = $outline[0]['#markup'] == 1 ? TRUE : FALSE;
  }

  if ($paragraph->hasField('field_size')) {
    $size = $variables['content']['field_size']; 
    $variables['size'] = $size[0]['#markup'] ?? '';
  }

  if ($paragraph->hasField('field_url')) {
    $url = $variables['content']['field_url'];
    $url = [
      'title' => $url[0]['#title'],
      'url' => $url[0]['#url'],
    ];
    $variables['url'] = $url;
  }
}