<?php

/**
 * @file
 * Provides functionality for the Vosix Components module.
 */

/**
 * Implements hook_theme().
 */
function vos_theme() {
  return [
    'vos_style_guide' => [
      'template' => 'vos-style-guide',
      'render element' => 'element',
    ],
  ];
}

/**
 * Implements hook_preprocess_paragraphs().
 */
function vosix_components_preprocess_paragraphs(array &$variables): void {
  /** @var \Drupal\paragraphs\Entity\Paragraph|null $paragraph */
  $paragraph = $variables['paragraph'] ?? NULL;
  if (!$paragraph) {
    return;
  }

  if ($paragraph->hasField('field_custom_classes')) {
    $custom_classes = $variables['content']['field_custom_classes'];
    $custom_classes = $custom_classes[0]['#context']['value'] ?? '';
    $custom_classes = explode(' ', $custom_classes);
    $variables['custom_classes'] = $custom_classes;
  }

  if ($paragraph->hasField('field_type')) {
    $type = $variables['content']['field_type'];
    if ($type['#formatter'] == 'list_key') {
      $variables['type'] = $type[0]['#markup'] ?? '';
    }
  }

  if ($paragraph->hasField('field_dismissible')) {
    $dismissible = $variables['content']['field_dismissible']; 
    $variables['dismissible'] = $dismissible[0]['#markup'] == 1 ? TRUE : FALSE;
  }
}
