<?php

/**
 * @file
 * Provides functionality for the Vosix Components Heading module.
 */

/**
 * Implements hook_preprocess_paragraph__HOOK().
 */
function vosix_components_heading_preprocess_paragraph__heading(array &$variables) {
  /** @var \Drupal\paragraphs\Entity\Paragraph|null $paragraph */
  $paragraph = $variables['paragraph'] ?? NULL;
  if (!$paragraph) {
    return;
  }

  if ($paragraph->hasField('field_heading_level')) {
    $level = $variables['content']['field_heading_level']; 
    $variables['heading_level'] = $level[0]['#markup'] ?? 'h2';
  }
}